export const constants = {
  ONE_DAY: 86400000,
  ARTICLE_CREATE: "Статья создана",
  ARTICLE_DELETE: "Статья удалена",
  ARTICLE_DELETE_ERROR: "Не удалоось удалить статью",
  ARTICLE_UPDATE: "Статья обновлена",
  ARTICLE_UPDATE_ERROR: "Не удалось обновить статью",
  ARTICLE_CREATE_ERROR: "Не удалось создать статью",
  MIN_LENGTH_ARTICLE_TITLE: 4,
  MIN_LENGTH_ARTICLE_BODY: 10,
  COMMENT_CREATE: "Комментарий создан",
  COMMENT_CREATE_ERROR: "Не удалось создать комментарий",
  COMMENT_DELETE: "Комментарий удалён",
  COMMENT_DELETE_ERROR: "Не удалось удалить комментарий",
  COMMENT_UPDATE: "Комментарий обновлён",
  COMMENT_UPDATE_ERROR: "Не удалось обновить комментарий",
};
